version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dieter
      POSTGRES_USER: postgres:alpine3.20
      POSTGRES_PASSWORD: meriaysha

  web:
    build: .
    command: gunicorn Dieter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
